config/routes.rb
Social::Application.routes.draw do
  resources :quizzes do
    member do
      post 'start'
      get 'question'
      post 'question'
      post 'answer'
      get 'end'
      post 'share'
    end
  end
  resources :quiz_results
  resources :activities, only: [:index]
  resources :activities do
    member do
      post 'read'
      post 'all_read'
    end
  end
  get "profiles/show"
  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/sign_in', to: 'devise/sessions#new', as: :sign_in
    get '/sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get '/sign_in' => 'devise/sessions#new', as: :new_user_session
    post '/sign_in' => 'devise/sessions#create', as: :user_session
    delete '/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    member do
       post 'like'
       post 'unlike'
    end
  end
  resources :statuses, path: 'updates'
  resources :statuses, path_names: { new: "create" }
  get 'feed', to: "statuses#index", as: :feed

  authenticated :user do
    root :to => "statuses#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  # User can only take quiz if logged in
  before_filter :authenticate_user!

  ##########################
  #  Rails CRUD Functions  #
  ##########################

  # Controls the quiz index view
  def index
    # Instance variables are declared here so that can be used by the view
    # Get all quizzes from the database and store them in the @quizzes variable
    @quizzes = Quiz.all
    # Get all quiz results from the database and store them in @quizresult
    @quizresult = QuizResult.all
  end

  # Controls the show quiz view - this is not really used, but it's here.
  def show
    # Get the quiz by its id and store it in @quiz
    @quiz = Quiz.find(params[:id])
  end

  # Controls the new view.
  def new
    @quiz = Quiz.new
  end

  # Controls the create function.
  def create
    # Creates a new quiz
    @quiz = Quiz.new(params[:quiz])
    # If the quiz saves without error
    if @quiz.save
      # Redirect to the quiz (uses the show view) and display a message
      redirect_to @quiz, notice: "Successfully created quiz."
    else
      # Else try again.
      render :new
    end
  end

  # Controls the edit view
  def edit
    # Gets the quiz and stores it in @quiz
    @quiz = Quiz.find(params[:id])
  end

  # Conrols the update function
  def update
    # Get the quiz by its id and store it in @quiz
    @quiz = Quiz.find(params[:id])
    # If the quiz updates without error
    if @quiz.update_attributes(params[:quiz])
      # Redirect to the quiz (uses the show view) and display a message
      redirect_to @quiz, notice: "Successfully updated quiz."
    else
      # Else try again.
      render :edit
    end
  end
  # Controls the destroy function
  def destroy
    # Get quiz by id and store it as @quiz
    @quiz = Quiz.find(params[:id])
    # Destroy it
    @quiz.destroy
    # Redirect to index, display message
    redirect_to quizzes_url, notice: "Successfully destroyed quiz."
  end

  ##################
  # Quiz Functions #
  ##################

  # Controls the start function
  def start
    # Get quiz by id and store it as @quiz
    @quiz = Quiz.find(params[:id])
    # Get the quiz array length and set it as a variable. Note we're not using session variables because the view doesn't need to interact with the total yet.
    total = @quiz.questions.length
    # If total is greater than 10, set it to 10. Else leave it unchanged. This ensures we get a max of 10 questions but doesn't freak out if there's only 4.
    if total > 10
      total = 10
    end
    # Get all the questions in @quiz and store them in an array called all
    all = @quiz.questions.find(:all).map {|x| x.id}
    # Session variables: Thess will persist across multiple views
    # Get the all array, sort it by random, truncate it at 10 and save it to the questions session variable
    session[:questions] = all.sort_by{rand}[0..(total-1)]
    # Set the total session variable to total
    session[:total]   = total
    # Set current question to 0
    session[:current] = 0
    # Set number of correct answers to 0
    session[:correct] = 0
    # Set score to 0
    session[:score]   = 0
    # Redirect to question 1
    redirect_to :action => "question"
  end
  # Controls the question view
  def question
    # Get current question number and set it to instance variable @current.
    @current  = session[:current]
    # get total questions and set it to @total
    @total    = session[:total]
    # Calculate progress as a percentage
    @progress = (@current+1) * 100 / @total
    # If we're done, redirect to the end action
    if @current >= @total
      redirect_to :action => "end"
      return
    end
    # Get the question from the array at position @current, e.g. Question 4 gets item 4 in the array
    @question = Question.find(session[:questions][@current])
    # get the answers from the answers table for the question and sort them randomly
    @answers = @question.answers.sort_by{rand}
    # Set the session variables question and answers to @question and @answers so that they will be remembered on the answers view.
    session[:question] = @question
    session[:answers] = @answers
  end

  # Controls the feedback view
  def answer
    # Get current question number and set it to instance variable @current.
    @current = session[:current]
    # get total questions and set it to @total
    @total   = session[:total]
    # Calculate progress as a percentage
    @progress = (@current+1) * 100 / @total
    # Get the user's answer passed via HTTP
    answerid = params[:answer]
    # Get the question and answer session variables
    @question = session[:question]
    @answers  = session[:answers]
    # Set @answer to answerid if it's not nil
    @answer = answerid ? Answer.find(answerid) : nil
    # If it's not nil and it is correct...
    if @answer and @answer.correct
      # set @correct to true
      @correct = true
      # and increment the total of correct answers
      session[:correct] += 1
    else
      # otherwise set @ correct to false
      @correct = false
    end
    # increment the current question
    session[:current] += 1
  end
  # Controls the end quiz view
  def end
    # Get quiz by id and store it as @quiz
    @quiz = Quiz.find(params[:id])
    # Get the number of correct answers and store it as @correct
    @correct = session[:correct]
    # Get the total number of questions and store it as @total
    @total   = session[:total]
    # Calculate the score as a percentage
    @score = @correct * 100 / @total
    # Call get_points passing the score variable to get the number of points earned
    @points = get_points(@score)
    # get current user and set them as @user
    @user = current_user
    # Give the user some points
    current_user.add_points(@points, category: 'Quizzes')
    # Set @next to false
    @next = false
    # if the score is high enough to unlock the next quiz...
    if @score > 75
      # set next to true.
      @next = true
    end
    # Create a Quiz Result
    @quizresult = QuizResult.create(user_id: @user.id, quiz_id: @quiz.id, score: @score, next_quiz: @next )
    # Set the session variable score to @score so that we can call the share function
    session[:score] = @score
  end

  # Caluculate the trophy classification
  def get_points(score)
    case
        # If score is greater than 75, give 30 points
        when score > 75
            return 30
        # If it's greater than 50, give 20 points
        when score > 50
            return 20
        # Otherwise give 10. Fun Revision loves a trier.
        else
            return 10
    end
  end
  # Controls the share functions
  def share
    # Get the quiz by id and store it in @quiz
    @quiz = Quiz.find(params[:id])
    # Get the current score and store it in @score
    @score = session[:score]
    # Call the get_badge helper passing the @score variable. Set the resulting string (gold, silver, bronze) as @badge
    @badge = view_context.get_badge(@score)
    # Get the quiz path and set it as @url
    @url = start_quiz_path(@quiz)
    # Spoilers. Sharing a result is really just creating a specifically formatted status. Things were going to get too complicated otherwise with polymorphic associations and nonsense like that. Set the status content as a string using the previously defined variables.
    @content = "<span class='fi-trophy #{@badge} left'></span>I got #{@score}% in #{@quiz.name}!<br><br><a href='#{@url}' data-method='post'>Can you beat my score?</a>"
    # Create a status.
    @trophy = current_user.statuses.create(content: @content.html_safe)
    # Create an activity with the action earned. This will appear in the activity feed as "User Name earned a trophy"
    current_user.create_activity(@trophy, 'earned')
    # redirect to the quiz index with a notice. Phew.
    redirect_to quizzes_url, notice: "Result shared."
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
    def get_badge(score)
        case
            when score > 75
                return "gold"
            when score > 50
                return "silver"
            else
                return "bronze"
        end
    end
    def link_to_add_fields(name, f, association)
        new_object = f.object.send(association).klass.new
        id = new_object.object_id
        fields = f.fields_for(association, new_object, child_index: id) do |builder|
          render(association.to_s.singularize + "_fields", f: builder)
        end
        link_to(name, '#', class: "add_fields tiny button", data: {id: id, fields: fields.gsub("\n", "")})
    end
end

app/views/quizzes/_answer_fields.html.erb
<fieldset>
    <legend>Answer</legend>
  <div class="row">
    <div class="small-8 columns">
        <!-- Answer content textbox -->
        <%= f.input_field :content, required: true  %>
    </div>
    <div class="small-2 columns">
        <!-- Checkbox to mark as correct -->
        <%= f.input :correct, as: :boolean %>
    </div>
    <div class="small-2 columns">
        <%= f.hidden_field :_destroy %>
        <%= link_to "remove", '#', class: "remove_fields tiny alert button" %>
    </div>
  </div>
</fieldset>

app/views/quizzes/_form.html.erb
<!-- Standard rails form setup -->
<%= simple_form_for @quiz do |f| %>
  <!-- displays any errors -->
  <%= f.error_notification %>
  <!-- Quiz name textbox -->
  <%= f.input :name, required: true %>
  <%= f.fields_for :questions do |builder| %>
    <!-- Renders a questions subform -->
    <%= render 'question_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Question", f, :questions %>

  <div class="actions">
  <hr>
    <%= f.submit class: 'large success button' %>
    <%= link_to "Cancel", quizzes_path,  class: 'large alert button' %>
  </div>
<% end %>

app/views/quizzes/_question_fields.html.erb
<fieldset>
  <legend>Question</legend>
    <div class="row">
        <div class="small-10 columns">
          <!-- Question content text area -->
          <%= f.input_field :content, required: true, as: :text  %>
        </div>
        <div class="small-2 columns">
          <%= f.hidden_field :_destroy %>
          <%= link_to "remove", '#', class: "remove_fields tiny alert button" %>
        </div>
        <div class="small-12 columns">
          <!-- if there's an attachment... -->
          <% if f.object.attachment? %>
            <label>Attached file</label>
            <!-- Display it... -->
            <%= image_tag f.object.attachment.url %>
          <% else %>
              <!-- Otherwise display an upload field -->
              <%= f.file_field :attachment %>
          <% end %>
        </div>
    </div>


  <%= f.fields_for :answers do |builder| %>
    <!-- We need to go deeper. Render some answer fields -->
    <%= render 'answer_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :answers %>
</fieldset>

app/views/quizzes/answer.html.erb
<div class="large-12 columns">
    <div class="card">
          <div class="ac-custom">
            <!-- Get question content -->
            <h3 id="question"><%= @question.content %></h3>
            <h4>
              <!-- If the users answer is correct display this... -->
              <% if @correct %>
               That's the right answer!
              <% else %>
                <!-- otherwise display this... -->
                Sorry, the's not the right answer.
              <% end %>
            </h4>
            <ul>
            <!-- Diplay each of the answers associated with the question -->
           <% @question.answers.each do |answer| %>
                  <!-- Highlight the right answer in green -->
                 <% if answer.correct %>
                  <li class="result success">
                  <!-- If not already highlighed, highlight the users answer in red -->
                 <% elsif answer == @answer %>
                  <li class="result alert">
                 <% else %>
                  <li class="result">
                 <% end %>
                  <span class="result-text"><%= answer.content %></span>
                </li>
              <% end %>
            </ul>
          <!-- Creates a form to send the user to the next question, quizzes controller and the question action -->
          <%= form_tag({:controller => "quizzes", :action => "question"}) do %>
            <div class="row">
              <div class="small-12 large-8 columns">
                <div class="progress round">
                  <span class="meter" style="width: <%= @progress %>%"></span>
                </div>
              </div>
              <div class="small-12 large-2 columns">
                <%= submit_tag("Continue", :class => "expand round success button") %>
              </div>
            </div>
        <% end %></div>
    </div>
</div>

app/views/quizzes/edit.html.erb
<div class="large-12 columns">
    <div class="card"><h1>Editing Quiz</h1>
        <div class="row">
    <div class="small-12 columns">
<%= render "form" %>    </div>
</div>
</div></div>

app/views/quizzes/end.html.erb
<div class="large-12 columns">
    <div class="card">
        <div class="result text-center">
            <h1>Quiz Results</h1>
            <!-- calls the get badge helper to get the right class for the trophy -->
            <span class="fi-trophy <%= get_badge(@score) %>"></span>
            <!-- Displays the score -->
            <p id="score">Your score: <%= @score %>%</p>
            <!-- displays the total correct -->
            <p id="question">You answered <%= @correct %> out of <%= @total %> questions correctly and got a <%= get_badge(@score) %> trophy!</p>
            <!-- displays the number of points earned -->
            <p>You got <%= @points %> points!</p>
            <!-- Posts to the share method to create a status using the above values. -->
            <%= link_to share_quiz_path(@quiz), :class => "success button", :method=> :post do%>
            <i class='fi-share'></i>  Share result
          <% end %>
          <%= link_to "Take another quiz", quizzes_path, :class => "secondary button" %>
        </div>
    </div>
</div>

app/views/quizzes/index.html.erb
<div class="large-12 columns">
    <div class="card"><h1>Quizzes</h1>
        <!-- For each quiz in @quizzes -->
        <% @quizzes.each do |quiz| %>
          <div class="article quizblock row">
                <div class="small-12 medium-9 columns">
                    <!-- Display the name -->
                    <h3><%= quiz.name %>
                    <!--If current user is admin... -->
                    <% if current_user.admin? %>
                    <!-- Show edit and delete controls -->
                        <div class="quizadmin">
                            <!-- edit quiz -->
                            <%= link_to "", edit_quiz_path(quiz), class: "admin fi-wrench so-edit", title: "Edit Quiz"%>
                            <!-- delete quiz -->
                            <%= link_to '', quiz, method: :delete, data: { confirm: 'Are you sure?' }, :class => "admin fi-x so-delete",title: "Delete Quiz" %>
                        </div>
                    <% end %>
                    </h3>
                </div>
                <!-- If layout wiggles to conditionally display an extra button if admin without the whole layout blowing up -->
                <div class="small-12 <% if current_user.admin? %>medium-3<% else %>medium-2 medium-offset-1<% end %> columns">
                    <!-- If current_user is admin -->
                    <% if current_user.admin? %>
                        <!-- Display a link to the quiz results -->
                        <%= link_to "Scores", quiz_result_path(quiz), class: "small button" %>
                    <% end %>
                    <!-- This is a bit of cheeky hackery. I couldn't get it working properly in time, so the quiz id is hardcoded in. See recommedations for details -->
                    <!-- if the quiz id is 1 -->
                    <% if quiz.id==1 %>
                        <!-- display a link to the quiz. Calls the start quiz method, which doesn't have a view. Start Quiz runs helpers like setting up the questions etc, then redirects to the first question when done. -->
                        <%= link_to "Take Quiz", start_quiz_path(quiz), class: "small success button",  method: "post" %>
                    <% else %>
                        <!-- for each quiz result in quiz results table -->
                        <% @quizresult.each do |qr| %>
                            <!-- If the current user has next quiz flag as true -->
                            <%if qr.user_id == current_user.id && qr.next_quiz == true %>
                                <!-- display a link to the quiz. Calls the start quiz method, which doesn't have a view. Start Quiz runs helpers like setting up the questions etc, then redirects to the first question when done. -->
                                <%= link_to "Take Quiz", start_quiz_path(quiz), class: "small success button",  method: "post" %>
                                <!-- Stop the loop. The user may have more than 1 attempt. We don't want to display multiple buttons -->
                                <% break %>
                            <% end %>
                        <% end %>

                    <%end%>

                </div>
          </div>
        <% end %>
        <!-- If the current user is admin -->
        <% if current_user.admin? %>
            <!-- display a link to create a new quiz -->
            <%= link_to 'New quiz', new_quiz_path, class: "small secondary button" %>
        <% end %>
    </div>
</div>

app/views/quizzes/new.html.erb
<div class="large-12 columns">
    <div class="card"><h1>New Quiz</h1>
<!-- render form partial -->
<%= render "form" %>
</div>
</div>

app/views/quizzes/question.html.erb
<div class="large-12 columns">
    <div class="card">
        <!-- Create a form using the questions controller and the answer method. When this is submitted it will pass the form data to this method. -->
        <%= form_tag({:controller => "quizzes", :action => "answer"}, class: "ac-custom ac-checkbox ac-checkmark") do %>
            <!-- Get display question -->
            <h3 id="question"><%= @question.content %></h3>
            <!-- If there's an attachment, display it too -->
            <% if @question.attachment? %>
              <%= image_tag @question.attachment.url %>
            <% end %>
            <ul>
            <!-- Display each answer as a radio button -->
           <% @question.answers.each do |answer| %>
                <li>
                <%= radio_button_tag(:answer, answer.id, checked = false, class:"check_this") %>
                <%= label_tag("answer_".concat(answer.id.to_s).to_sym, answer.content) %>
                </li>
          <% end %>
            </ul>
          <div class="row">
            <div class="small-12 large-8 columns">
                <div class="progress round">
                  <!-- Display a progress bar using the @progress variable calculated in the controller -->
                  <span class="meter" style="width: <%= @progress %>%"></span>
                </div>
            </div>
            <div class="small-12 large-2 columns">
                <%= submit_tag("Continue", :class => "expand round success disabled button") %>
            </div>

          </div>
        <% end %>
    </div>
</div>

app/views/quizzes/show.html.erb
<div class="large-12 columns">
  <div class="card">
    <h1><%= @quiz.name %></h1>

    <ol class="questions">
    <!-- For each question in @quiz -->
    <% @quiz.questions.each do |question| %>
    <li>
      <!-- display the content -->
      <%= question.content %>
      <ol class="answers">
        <!-- For each answer associated with the question -->
        <% question.answers.each do |answer| %>
        <!-- display the content -->
        <li><%= answer.content %></li>
        <% end %>
      </ol>
    </li>
    <% end %>
  </ol>

  <%= link_to 'Edit', edit_quiz_path(@quiz) %> |
  <%= link_to 'Back to Quiz', quizzes_path %>
  </div>
</div>