config/routes.rb
Social::Application.routes.draw do
  resources :quizzes do
    member do
      post 'start'
      get 'question'
      post 'question'
      post 'answer'
      get 'end'
      post 'share'
    end
  end
  resources :quiz_results
  resources :activities, only: [:index]
  resources :activities do
    member do
      post 'read'
      post 'all_read'
    end
  end
  get "profiles/show"
  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/sign_in', to: 'devise/sessions#new', as: :sign_in
    get '/sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get '/sign_in' => 'devise/sessions#new', as: :new_user_session
    post '/sign_in' => 'devise/sessions#create', as: :user_session
    delete '/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    member do
       post 'like'
       post 'unlike'
    end
  end
  resources :statuses, path: 'updates'
  resources :statuses, path_names: { new: "create" }
  get 'feed', to: "statuses#index", as: :feed

  authenticated :user do
    root :to => "statuses#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def show
      	@user = User.find_by_profile_name(params[:id])
        @user_friendships = @user.user_friendships.all
      	if @user
      		@statuses = @user.statuses.all(:order => 'updated_at DESC')
      		render action: :show
      	else
      		render file: 'public/404', status: 404, formats: [:html]
        end
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="medium-6 large-4 columns ">
	<div class="profile-card text-center radius">
		<div class="banner" style="<%= show_user_banner %>"></div>
		<%= image_tag @user.avatar.url(:thumb),:class=> "profile-feed" %>
		<h1><%= @user.full_name %></h1>
		<h3 class="subheader"><%= @user.points %> points</h3>
		<% if signed_in? %>
			<div id="friend_status">
				<% unless @user == current_user %>
					<% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
						<%= link_to "Edit Friendship", edit_user_friendship_path(friend_id: @user), class: 'tiny success round button' %>
					<% else %>
						<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'tiny success round button', id:'add_friendship', data: {friend_id: @user.to_param} %>
					<% end %>
				<% end %>
			</div>
		<% end %>
	</div>
	<div class="row">
		<div class="small-12 columns">
			<div class="card clearfix">
				<h2><%= @user.first_name %>'s Friends</h2>
				<% @user_friendships.each do |friendship| %>
					<% friend = friendship.friend %>
					<% if friendship.state?(:accepted) %>
						<div class="small-6 columns">

							<div class="profile-friends">
								<%= link_to profile_path(friend) do %>
									<div class="img">
										<%= image_tag(friend.avatar.url(:thumb)) %>
									</div>
									<div class="info">
							          <h3><%= friend.full_name %></h3>
							        </div>
							    <% end %>
							</div>

						</div>
					<% end %>

				<% end %>
			</div>
		</div>
	</div>
</div>
<div class="medium-6 large-8 columns">
	<div class="row status">
	<% if @statuses %>
		<% @statuses.each do |status|%>
			<article class="medium-12 large-6 columns status-outer" id="status-id-<%= status.id %>">
			<div class="bannerhint <% if signed_in? && status.user == current_user %>peek<% end %>" style="background-image:url('<%= status.user.banner.url(:normal)%>');">
				<% if can_edit_status?(status) %>
				       <div class="admin-box">
				        <%= link_to '', edit_status_path(status), :class=> "admin fi-wrench so-edit" %>
				      	<%= link_to '', status, method: :delete, data: { confirm: 'Are you sure?' }, :class => "admin fi-x so-delete", :remote=>true %></div>
				<% end %>
			</div>
			<div class="feed-card status">

				<div class="banner clearfix">

					<div class="postbox"><%=link_to image_tag(status.user.avatar.url(:thumb),:class=> "profile-feed"),profile_path(status.user) %></div>

			    	<div class="postbox"><h4><%= status.user.full_name %></h4>
			    		<small><%= time_ago_in_words(status.created_at) + " ago" %></small></div>
					<div class="meta">
						<span id="like-button-<%= status.id %>" class="likes-button">
							<%if current_user.voted_up_on? status%>
							    <%=  render '/statuses/unlike', :status => status %>
							<%else%>
							    <%= render 'statuses/like', :status => status %>
							<%end%>
						</span>
						<span id="likes-count-<%= status.id %>" class="likes-count <%if current_user.voted_up_on? status%>unlike<% end %>"><%= status.likes.size %></span>
					</div>
				</div>

			    <div class="postcontent">
					<p><%= status.content.html_safe %></p>
				</div>

			  </div>
			</article>

		<% end %>
	<% else %>
		<h2>Nothing here</h2>
	<% end %>
</div>
</div>