config/routes.rb
Social::Application.routes.draw do
  resources :quizzes do
    member do
      post 'start'
      get 'question'
      post 'question'
      post 'answer'
      get 'end'
      post 'share'
    end
  end
  resources :quiz_results
  resources :activities, only: [:index]
  resources :activities do
    member do
      post 'read'
      post 'all_read'
    end
  end
  get "profiles/show"
  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/sign_in', to: 'devise/sessions#new', as: :sign_in
    get '/sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get '/sign_in' => 'devise/sessions#new', as: :new_user_session
    post '/sign_in' => 'devise/sessions#create', as: :user_session
    delete '/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    member do
       post 'like'
       post 'unlike'
    end
  end
  resources :statuses, path: 'updates'
  resources :statuses, path_names: { new: "create" }
  get 'feed', to: "statuses#index", as: :feed

  authenticated :user do
    root :to => "statuses#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:index, :new, :create, :edit, :update]

  # GET /statuses
  # GET /statuses.json
  def index
    @status = Status.new
    @statuses = Status.paginate(:per_page => 9, :page => params[:page]).order('updated_at DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
      format.js
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = current_user.statuses.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])
    respond_to do |format|
      if @status.save
        current_user.create_activity(@status, 'created')
        current_user.add_points(5, category: 'Social')
        format.html { redirect_to statuses_url, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
        format.js
      else
        flash.now[:notice] = "Houston, we have a problem."
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
        format.js   { render "form_errors.js.erb" }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id)
    end
    respond_to do |format|
      if @status.update_attributes(params[:status])
        current_user.create_activity(@status, 'updated')
        format.html { redirect_to statuses_url, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = current_user.statuses.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
      format.js
    end
  end

  def like
    @status = Status.find(params[:id])
    current_user.upvotes @status
    current_user.create_activity(@status, 'liked')
    current_user.add_points(2, category: 'Social')
    if current_user != @status.user
      @status.user.add_points(2, category: 'Social')
    end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def unlike
    @status = Status.find(params[:id])
    current_user.downvotes @status
    current_user.subtract_points(2, category: 'Social')
    if current_user != @status.user
      @status.user.subtract_points(2, category: 'Social')
    end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
    def can_display_status?(status)
        signed_in? && status.user == current_user || signed_in? && current_user.is_friends?(status.user) && !current_user.has_blocked?(status.user) || signed_in? && current_user.admin?
    end
    def can_edit_status?(status)
        signed_in? && current_user.admin? || signed_in? && status.user == current_user
    end
    def readable_points
        if current_user.points == 0
            "You don't have any points yet."
        else
            "You have #{current_user.points} points."
        end
    end
end

app/views/statuses/_create.html.erb
<article class="small-12 medium-6 large-4 columns status-outer new" id="status-id-<%= status.id %>">
    <div class="bannerhint <% if signed_in? && status.user == current_user %>peek<% end %>" style="background-image:url('<%= status.user.banner.url(:normal)%>');">
        <% if signed_in? && status.user == current_user %>
               <div class="admin-box">
                <%= link_to '', edit_status_path(status), :class=> "admin fi-wrench so-edit" %>
                <%= link_to '', status, method: :delete, data: { confirm: 'Are you sure?' }, :class => "admin fi-x so-delete", :remote=>true %></div>
        <% end %>
    </div>
    <div class="feed-card status">

        <div class="banner clearfix">

            <div class="postbox"><%=link_to image_tag(status.user.avatar.url(:thumb),:class=> "profile-feed"),profile_path(status.user) %></div>

            <div class="postbox"><h4><%= status.user.full_name %></h4>
                <small><%= time_ago_in_words(status.created_at) + " ago" %></small></div>
            <div class="meta">
                <span id="like-button-<%= status.id %>" class="likes-button">
                    <%if current_user.voted_up_on? status%>
                        <%=  render 'unlike', :status => status %>
                    <%else%>
                        <%= render 'like', :status => status %>
                    <%end%>
                </span>
                <span id="likes-count-<%= status.id %>" class="likes-count <%if current_user.voted_up_on? status%>unlike<% end %>"><%= status.likes.size %></span>
            </div>
        </div>

        <div class="postcontent">
            <p><%= status.content %></p>
        </div>
    </div>
</article>

app/views/statuses/_like.html.erb
<!-- Link to the like status action in the controller with a post method. Remote: true allows the action to be performed by javascript calling the like.js.erb file -->
<%= link_to '', like_status_path(status), method: :post,:class => "fi-heart like",remote: true %>

app/views/statuses/_points.html.erb
<%= readable_points %>

app/views/statuses/_status.html.erb
<% if can_display_status?(status) %>
    <article class="small-12 medium-6 large-4 columns status-outer" id="status-id-<%= status.id %>" data-equalizer-watch>
        <div class="bannerhint <% if can_edit_status?(status) %>peek<% end %>" style="background-image:url('<%= status.user.banner.url(:normal)%>');">
        <% if can_edit_status?(status) %>
               <div class="admin-box">
                <%= link_to '', edit_status_path(status), :class=> "admin fi-wrench so-edit" %>
                <%= link_to '', status, method: :delete, data: { confirm: 'Are you sure?' }, :class => "admin fi-x so-delete", :remote=>true %></div>
        <% end %>
        </div>
        <div class="feed-card status">

            <div class="banner clearfix">

                <div class="postbox">
                    <%=link_to image_tag(status.user.avatar.url(:thumb),:class=> "profile-feed"),profile_path(status.user) %>
                </div>
                <div class="postbox">
                    <h4><%= status.user.full_name %></h4>
                    <small><%= time_ago_in_words(status.created_at) + " ago" %></small>
                </div>
                <div class="meta">
                    <span id="like-button-<%= status.id %>" class="likes-button">
                        <%if current_user.voted_up_on? status%>
                            <%=  render 'unlike', :status => status %>
                        <%else%>
                            <%= render 'like', :status => status %>
                        <%end%>
                    </span>
                    <span id="likes-count-<%= status.id %>" class="likes-count <%if current_user.voted_up_on? status%>unlike<% end %>"><%= status.likes.size %></span>
                </div>
            </div>
            <div class="postcontent">
                <p><%= status.content.html_safe %></p>
            </div>
        </div>
    </article>
<% end %>

app/views/statuses/_unlike.html.erb
<%= link_to '', unlike_status_path(status), method: :post,:class => "fi-heart unlike",remote: true %>

app/views/statuses/create.js.erb
$('small.error').hide();
$(".new-status-box").removeClass('open').val('');
$('.input-box').removeClass('error');
$('#statuses').prepend("<%= escape_javascript(render 'create', :status => @status) %>");
$(".status-outer.new").fadeIn().removeClass('new');
$('#points').html('<%= j render partial: "points" %>');

app/views/statuses/destroy.js.erb
$("#status-id-<%= @status.id %>").fadeOut();

app/views/statuses/edit.html.erb
<div class="large-6 large-centered columns card">
	<h1>Editing status</h1>

<%= render 'form' %>
<%= link_to 'Back', statuses_path, :class => "tiny secondary button" %>
</div>

app/views/statuses/form_errors.js.erb
$('small.error').css("display", "block");
$('.input-box').addClass('error');

app/views/statuses/index.js.erb
$('#statuses').append('<%= j render(@statuses) %>');
<% if @statuses.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@statuses) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/statuses/like.js.erb
// Renders the unlike partial (pink heart).
$("#like-button-<%= @status.id %>").html("<%= escape_javascript(render 'unlike', :status => @status) %>")
// Removes and readds the activated class, which runs the animation.
$("#like-button-<%= @status.id %> a").removeClass('activated').addClass('activated');
// re-renders the likes count, updating it and adds the unlike class (pink text)
$("#likes-count-<%= @status.id %>").html('<%= @status.likes.size %>').addClass('unlike');
// re-renders the points partial updating it.
$('#points').html('<%= j render partial: "points" %>');



app/views/statuses/show.html.erb
<article class="small-12 medium-8 large-6 small-centered columns status-outer" id="status-id-<%= @status.id %>" style="margin-top:20px;">
	<div class="bannerhint <% if signed_in? && @status.user == current_user %>peek<% end %>" style="background-image:url('<%= @status.user.banner.url(:normal)%>');">
		<% if can_edit_status?(@status) %>
		       <div class="admin-box">
		        <%= link_to '', edit_status_path(@status), :class=> "admin fi-wrench so-edit" %>
		      	<%= link_to '', @status, method: :delete, data: { confirm: 'Are you sure?' }, :class => "admin fi-x so-delete", :remote=>true %></div>
		<% end %>
	</div>
	<div class="feed-card status">

		<div class="banner clearfix">

			<div class="postbox"><%=link_to image_tag(@status.user.avatar.url(:thumb),:class=> "profile-feed"),profile_path(@status.user) %></div>

	    	<div class="postbox"><h4><%= @status.user.full_name %></h4>
	    		<small><%= time_ago_in_words(@status.created_at) + " ago" %></small></div>
			<div class="meta">
				<span id="like-button-<%= @status.id %>" class="likes-button">
					<%if current_user.voted_up_on? @status%>
					    <%=  render 'unlike', :status => @status %>
					<%else%>
					    <%= render 'like', :status => @status %>
					<%end%>
				</span>
				<span id="likes-count-<%= @status.id %>" class="likes-count <%if current_user.voted_up_on? @status%>unlike<% end %>"><%= @status.likes.size %></span>
			</div>
		</div>

	    <div class="postcontent">
			<p><%= @status.content.html_safe %></p>
		</div>

	</div>
</article>

app/views/statuses/toggle.js.erb
$(document).ready(function() {$(".likeButton").html("<%= escape_javascript render('like_button') %>");});

app/views/statuses/unlike.js.erb
$("#like-button-<%= @status.id %>").html('<%= escape_javascript(render 'like', :status => @status) %>');
$("#like-button-<%= @status.id %> a").removeClass('activated').addClass('activated');
$("#likes-count-<%= @status.id %>").html('<%= @status.likes.size %>').removeClass('unlike');
$('#points').html('<%= j render partial: "points" %>');