config/routes.rb
Social::Application.routes.draw do
  resources :quizzes do
    member do
      post 'start'
      get 'question'
      post 'question'
      post 'answer'
      get 'end'
      post 'share'
    end
  end
  resources :quiz_results
  resources :activities, only: [:index]
  resources :activities do
    member do
      post 'read'
      post 'all_read'
    end
  end
  get "profiles/show"
  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/sign_in', to: 'devise/sessions#new', as: :sign_in
    get '/sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get '/sign_in' => 'devise/sessions#new', as: :new_user_session
    post '/sign_in' => 'devise/sessions#create', as: :user_session
    delete '/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    member do
       post 'like'
       post 'unlike'
    end
  end
  resources :statuses, path: 'updates'
  resources :statuses, path_names: { new: "create" }
  get 'feed', to: "statuses#index", as: :feed

  authenticated :user do
    root :to => "statuses#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/_flash.html.erb
<% flash.each do | type, message | %>
  <div class="alert-box <%= flash_class type %>" data-alert><%= message %><a href="#" class="close">&times;</a></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Fun Revision" %></title>
    <link rel="icon" type="image/png" href="<%= asset_path 'favicon.png' %>" />
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div class="contain-to-grid">
      <nav class="menu row">
        <section class="title medium-4 columns">
            <h1><%= link_to image_tag(asset_path 'logo.png'), feed_path %></h1>
        </section>
        <section class="medium-8 columns">
          <div class="menu-section">
            <ul>
              <% if user_signed_in? %>

              <li>
                <a data-dropdown="drop1" class="dropdown profile-bar" title="<%= current_user.full_name %>">
                  <%= image_tag current_user.avatar.url(:thumb),:class=> "profile-feed menu"%>
                </a>
                <ul id="drop1" data-dropdown-content class="f-dropdown">
                  <li><h4><%= current_user.full_name %></h4></li>
                  <li><%= link_to "Activity Feed", activities_path %></li>
                  <li><%= link_to "View Profile", profile_path(current_user) %></li>
                  <li><%= link_to "Edit Details", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
              <li class="iconic"  id="activity-feed">
                <a href="#" data-dropdown="drop2">
                  <span class="fi-sound lightgreen menu-item" title="Notifications"></span>
                  <div id="count"></div>
                </a>
                <div id="drop2" data-dropdown-content class="f-dropdown content">
                  <div id="subtle-notif">
                    <i class="fi-sound"></i>
                    <p>Nothing here!</p>
                  </div>
                </div>
              </li>
              <li class="iconic">
                <%= link_to quizzes_path do %>
                  <span class="fi-trophy has_tip midgreen menu-item" title="Quizzes"></span>
                <% end %>
              </li>
              <li class="iconic">
                <%= link_to user_friendships_path do %>
                  <span class="fi-torsos-all has_tip darkgreen menu-item" title="Friends"></span>
                <% end %>
              </li>


              <% else %>
              <li><%= link_to "Register", register_path, class: "button success" %></li>
              <li><%= link_to "Sign In", sign_in_path %></li>
              <% end %>
            </ul>
          </div>
        </section>
      </nav>
    </div>
    <div class="row">

      <div class="large-12 columns" id="notice">
        <% flash.each do | type, message | %>
          <%= render :partial => 'layouts/flash' , :locals => { :flash => flash , :type => type} %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <%= yield %>
  </div>
    <%= javascript_include_tag "application" %>
  </body>
  <script id="activities-template" type="text/x-handlebars-template">
      <div id="dropcontain">
        <li><a href="{{activityFeedLink}}">All Activity</a></li>
        <li class="divider"></li>
        {{#each activities}}
          {{activityLink}}
        {{/each}}


      </div>
  </script>
  <script id="count-template" type="text/x-handlebars-template">{{count}}</script>
   <script id="no-activities-template" type="text/x-handlebars-template">
      <div id="subtle-notif">
        <i class="fi-sound"></i>
        <p>Nothing here!</p>
      </div>
  </script>
</html>